
- name: Obtener información del sistema
  hosts: nodo1
  gather_facts: False
  tasks:
   - name: Ejecutar el comando ls -la
     command: ls -la
     register: resu

   - name: Mostrar
     debug:
      var: resu